site_name: CD-Moj

repo_name: "cd-moj.docs"
repo_url: "https://github.com/cd-moj/cd-moj.docs"

theme:
  name: material
  language: "pt"
  features: navigation.tabs
  icon:
    #logo: assets/logoCdMoj
    #repo: fontawesome/brands/github
  palette:
    primary: "Orange"
    accent: "Orange"
  font:
    text: "Montserrat"
    code: "sans-serif"

extra_css:
  - stylesheets/styles.css

nav:
  - Início: index.md
  - Instalação:
    - Instalação: steps/instalacao.md
  - Configuração:
    - Configuração: steps/configuracao.md
    - Erros: steps/permissions.md
  - Sobre:
    - Sobre cd moj: steps/aboutCdMoj.md
    - Judge: steps/judge.md
  - Contest:
    - Contest: steps/contest.md  
  - Contribuição: steps/mkdocs.md

dev_addr: "0.0.0.0:8000"
