site_name: CD-Moj

repo_name: "cd-moj.docs"
repo_url: "https://github.com/cd-moj/cd-moj.docs"

markdown_extensions:
  - pymdownx.pathconverter:
      base_path: 'cd-moj.docs'
      relative_path: ''
      absolute: true
      tags: 'a script img link object embed'

theme:
  name: material
  language: "pt"
  features: navigation.tabs
  icon:
    #logo: assets/logoCdMoj
    #repo: fontawesome/brands/github
  palette:
    primary: "Orange"
    accent: "Orange"
  font:
    text: "Montserrat"
    code: "sans-serif"

extra_css:
  - stylesheets/styles.css

nav:
  - Início: index.md

  - Usuário:
    - Sobre: steps/aboutCdMoj.md

  - Administrador:
    - Subindo Contest: steps/contestAdmin.md

  - Desenvolvedor:
    - Instalação: steps/instalacao.md
    - Configuração: steps/configuracao.md
    - MkDocs: steps/mkdocs.md
    - Contribuição: steps/contribuicao.md
    - Judge: steps/judge.md
    - Contest: steps/contest.md
    - Simular: steps/simular.md
  
  - Contribuição:
    - Contribuidores: steps/contribuidores.md

dev_addr: "0.0.0.0:8000"
